---
- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  
  - name: Curl website and Fail if 'Ansible has done its job' is not in the page content
    uri:
      url: "http://{{ openstack_info.ansible_facts.openstack_servers[0].public_v4 }}"
      return_content: yes
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
