- hosts: tag_AnsibleGroup_frontend
  gather_facts: false
  tasks:
  - name: Curl website and Fail if 'Ansible has done its job' is not in the page content
    uri:
      url: "http://{{ inventory_hostname }}"
      return_content: yes
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
